/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSubmitRouteImport } from './routes/articles/submit'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ManageAdminLayoutRouteRouteImport } from './routes/manage._admin-layout/route'
import { Route as ManageAdminLayoutPeopleRouteImport } from './routes/manage._admin-layout/people'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ManageAdminLayoutAStatusRouteImport } from './routes/manage._admin-layout/a.$status'
import { Route as ManageAdminLayoutAEditIdRouteRouteImport } from './routes/manage._admin-layout/a.edit.$id/route'
import { Route as ManageAdminLayoutAEditIdIndexRouteImport } from './routes/manage._admin-layout/a.edit.$id/index'
import { Route as ManageAdminLayoutAEditIdSeoRouteImport } from './routes/manage._admin-layout/a.edit.$id/seo'
import { Route as ManageAdminLayoutAEditIdPublishingRouteImport } from './routes/manage._admin-layout/a.edit.$id/publishing'
import { Route as ManageAdminLayoutAEditIdLayoutRouteImport } from './routes/manage._admin-layout/a.edit.$id/layout'
import { Route as ManageAdminLayoutAEditIdContentRouteImport } from './routes/manage._admin-layout/a.edit.$id/content'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSubmitRoute = ArticlesSubmitRouteImport.update({
  id: '/articles/submit',
  path: '/articles/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminLayoutRouteRoute = ManageAdminLayoutRouteRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAdminLayoutPeopleRoute = ManageAdminLayoutPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ManageAdminLayoutRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminLayoutAStatusRoute =
  ManageAdminLayoutAStatusRouteImport.update({
    id: '/a/$status',
    path: '/a/$status',
    getParentRoute: () => ManageAdminLayoutRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdRouteRoute =
  ManageAdminLayoutAEditIdRouteRouteImport.update({
    id: '/a/edit/$id',
    path: '/a/edit/$id',
    getParentRoute: () => ManageAdminLayoutRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdIndexRoute =
  ManageAdminLayoutAEditIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManageAdminLayoutAEditIdRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdSeoRoute =
  ManageAdminLayoutAEditIdSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => ManageAdminLayoutAEditIdRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdPublishingRoute =
  ManageAdminLayoutAEditIdPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => ManageAdminLayoutAEditIdRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdLayoutRoute =
  ManageAdminLayoutAEditIdLayoutRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => ManageAdminLayoutAEditIdRouteRoute,
  } as any)
const ManageAdminLayoutAEditIdContentRoute =
  ManageAdminLayoutAEditIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => ManageAdminLayoutAEditIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/a/$status': typeof ManageAdminLayoutAStatusRoute
  '/manage/a/edit/$id': typeof ManageAdminLayoutAEditIdRouteRouteWithChildren
  '/manage/a/edit/$id/content': typeof ManageAdminLayoutAEditIdContentRoute
  '/manage/a/edit/$id/layout': typeof ManageAdminLayoutAEditIdLayoutRoute
  '/manage/a/edit/$id/publishing': typeof ManageAdminLayoutAEditIdPublishingRoute
  '/manage/a/edit/$id/seo': typeof ManageAdminLayoutAEditIdSeoRoute
  '/manage/a/edit/$id/': typeof ManageAdminLayoutAEditIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/a/$status': typeof ManageAdminLayoutAStatusRoute
  '/manage/a/edit/$id/content': typeof ManageAdminLayoutAEditIdContentRoute
  '/manage/a/edit/$id/layout': typeof ManageAdminLayoutAEditIdLayoutRoute
  '/manage/a/edit/$id/publishing': typeof ManageAdminLayoutAEditIdPublishingRoute
  '/manage/a/edit/$id/seo': typeof ManageAdminLayoutAEditIdSeoRoute
  '/manage/a/edit/$id': typeof ManageAdminLayoutAEditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/links': typeof LinksRoute
  '/manage/_admin-layout': typeof ManageAdminLayoutRouteRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/_admin-layout/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/_admin-layout/a/$status': typeof ManageAdminLayoutAStatusRoute
  '/manage/_admin-layout/a/edit/$id': typeof ManageAdminLayoutAEditIdRouteRouteWithChildren
  '/manage/_admin-layout/a/edit/$id/content': typeof ManageAdminLayoutAEditIdContentRoute
  '/manage/_admin-layout/a/edit/$id/layout': typeof ManageAdminLayoutAEditIdLayoutRoute
  '/manage/_admin-layout/a/edit/$id/publishing': typeof ManageAdminLayoutAEditIdPublishingRoute
  '/manage/_admin-layout/a/edit/$id/seo': typeof ManageAdminLayoutAEditIdSeoRoute
  '/manage/_admin-layout/a/edit/$id/': typeof ManageAdminLayoutAEditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/links'
    | '/manage'
    | '/api/uploadthing'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/people'
    | '/manage/a/$status'
    | '/manage/a/edit/$id'
    | '/manage/a/edit/$id/content'
    | '/manage/a/edit/$id/layout'
    | '/manage/a/edit/$id/publishing'
    | '/manage/a/edit/$id/seo'
    | '/manage/a/edit/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/links'
    | '/manage'
    | '/api/uploadthing'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/people'
    | '/manage/a/$status'
    | '/manage/a/edit/$id/content'
    | '/manage/a/edit/$id/layout'
    | '/manage/a/edit/$id/publishing'
    | '/manage/a/edit/$id/seo'
    | '/manage/a/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/links'
    | '/manage/_admin-layout'
    | '/api/uploadthing'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/_admin-layout/people'
    | '/manage/_admin-layout/a/$status'
    | '/manage/_admin-layout/a/edit/$id'
    | '/manage/_admin-layout/a/edit/$id/content'
    | '/manage/_admin-layout/a/edit/$id/layout'
    | '/manage/_admin-layout/a/edit/$id/publishing'
    | '/manage/_admin-layout/a/edit/$id/seo'
    | '/manage/_admin-layout/a/edit/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinksRoute: typeof LinksRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesSubmitRoute: typeof ArticlesSubmitRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/submit': {
      id: '/articles/submit'
      path: '/articles/submit'
      fullPath: '/articles/submit'
      preLoaderRoute: typeof ArticlesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/_admin-layout': {
      id: '/manage/_admin-layout'
      path: ''
      fullPath: '/manage'
      preLoaderRoute: typeof ManageAdminLayoutRouteRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/_admin-layout/people': {
      id: '/manage/_admin-layout/people'
      path: '/people'
      fullPath: '/manage/people'
      preLoaderRoute: typeof ManageAdminLayoutPeopleRouteImport
      parentRoute: typeof ManageAdminLayoutRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/_admin-layout/a/$status': {
      id: '/manage/_admin-layout/a/$status'
      path: '/a/$status'
      fullPath: '/manage/a/$status'
      preLoaderRoute: typeof ManageAdminLayoutAStatusRouteImport
      parentRoute: typeof ManageAdminLayoutRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id': {
      id: '/manage/_admin-layout/a/edit/$id'
      path: '/a/edit/$id'
      fullPath: '/manage/a/edit/$id'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdRouteRouteImport
      parentRoute: typeof ManageAdminLayoutRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id/': {
      id: '/manage/_admin-layout/a/edit/$id/'
      path: '/'
      fullPath: '/manage/a/edit/$id/'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdIndexRouteImport
      parentRoute: typeof ManageAdminLayoutAEditIdRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id/seo': {
      id: '/manage/_admin-layout/a/edit/$id/seo'
      path: '/seo'
      fullPath: '/manage/a/edit/$id/seo'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdSeoRouteImport
      parentRoute: typeof ManageAdminLayoutAEditIdRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id/publishing': {
      id: '/manage/_admin-layout/a/edit/$id/publishing'
      path: '/publishing'
      fullPath: '/manage/a/edit/$id/publishing'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdPublishingRouteImport
      parentRoute: typeof ManageAdminLayoutAEditIdRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id/layout': {
      id: '/manage/_admin-layout/a/edit/$id/layout'
      path: '/layout'
      fullPath: '/manage/a/edit/$id/layout'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdLayoutRouteImport
      parentRoute: typeof ManageAdminLayoutAEditIdRouteRoute
    }
    '/manage/_admin-layout/a/edit/$id/content': {
      id: '/manage/_admin-layout/a/edit/$id/content'
      path: '/content'
      fullPath: '/manage/a/edit/$id/content'
      preLoaderRoute: typeof ManageAdminLayoutAEditIdContentRouteImport
      parentRoute: typeof ManageAdminLayoutAEditIdRouteRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinksRoute: LinksRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesSubmitRoute: ArticlesSubmitRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
