/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ArticlesIndexImport } from './routes/articles/index'
import { Route as ArticlesSubmitImport } from './routes/articles/submit'
import { Route as ArticlesSlugImport } from './routes/articles/$slug'
import { Route as ArticlesPublishIdImport } from './routes/articles/publish.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIndexRoute = ArticlesIndexImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesSubmitRoute = ArticlesSubmitImport.update({
  id: '/articles/submit',
  path: '/articles/submit',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesSlugRoute = ArticlesSlugImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesPublishIdRoute = ArticlesPublishIdImport.update({
  id: '/articles/publish/$id',
  path: '/articles/publish/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugImport
      parentRoute: typeof rootRoute
    }
    '/articles/submit': {
      id: '/articles/submit'
      path: '/articles/submit'
      fullPath: '/articles/submit'
      preLoaderRoute: typeof ArticlesSubmitImport
      parentRoute: typeof rootRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/publish/$id': {
      id: '/articles/publish/$id'
      path: '/articles/publish/$id'
      fullPath: '/articles/publish/$id'
      preLoaderRoute: typeof ArticlesPublishIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/articles/publish/$id': typeof ArticlesPublishIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/articles/publish/$id': typeof ArticlesPublishIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/articles/publish/$id': typeof ArticlesPublishIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/articles/publish/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/articles/publish/$id'
  id:
    | '__root__'
    | '/'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles/'
    | '/articles/publish/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesSubmitRoute: typeof ArticlesSubmitRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ArticlesPublishIdRoute: typeof ArticlesPublishIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesSubmitRoute: ArticlesSubmitRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ArticlesPublishIdRoute: ArticlesPublishIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/articles/$slug",
        "/articles/submit",
        "/articles/",
        "/articles/publish/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/articles/$slug": {
      "filePath": "articles/$slug.tsx"
    },
    "/articles/submit": {
      "filePath": "articles/submit.tsx"
    },
    "/articles/": {
      "filePath": "articles/index.tsx"
    },
    "/articles/publish/$id": {
      "filePath": "articles/publish.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
