/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ArticlesIndexImport } from './routes/articles/index'
import { Route as ArticlesSubmitImport } from './routes/articles/submit'
import { Route as ArticlesSlugImport } from './routes/articles/$slug'
import { Route as ManageAdminLayoutRouteImport } from './routes/manage._admin-layout/route'
import { Route as ManageAdminLayoutDraftsIndexImport } from './routes/manage._admin-layout/drafts/index'
import { Route as ManageAdminLayoutDraftsPublishIdImport } from './routes/manage._admin-layout/drafts/publish.$id'

// Create Virtual Routes

const ManageImport = createFileRoute('/manage')()

// Create/Update Routes

const ManageRoute = ManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIndexRoute = ArticlesIndexImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesSubmitRoute = ArticlesSubmitImport.update({
  id: '/articles/submit',
  path: '/articles/submit',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesSlugRoute = ArticlesSlugImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ManageAdminLayoutRouteRoute = ManageAdminLayoutRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => ManageRoute,
} as any)

const ManageAdminLayoutDraftsIndexRoute =
  ManageAdminLayoutDraftsIndexImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => ManageAdminLayoutRouteRoute,
  } as any)

const ManageAdminLayoutDraftsPublishIdRoute =
  ManageAdminLayoutDraftsPublishIdImport.update({
    id: '/drafts/publish/$id',
    path: '/drafts/publish/$id',
    getParentRoute: () => ManageAdminLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageImport
      parentRoute: typeof rootRoute
    }
    '/manage/_admin-layout': {
      id: '/manage/_admin-layout'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageAdminLayoutRouteImport
      parentRoute: typeof ManageRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugImport
      parentRoute: typeof rootRoute
    }
    '/articles/submit': {
      id: '/articles/submit'
      path: '/articles/submit'
      fullPath: '/articles/submit'
      preLoaderRoute: typeof ArticlesSubmitImport
      parentRoute: typeof rootRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexImport
      parentRoute: typeof rootRoute
    }
    '/manage/_admin-layout/drafts/': {
      id: '/manage/_admin-layout/drafts/'
      path: '/drafts'
      fullPath: '/manage/drafts'
      preLoaderRoute: typeof ManageAdminLayoutDraftsIndexImport
      parentRoute: typeof ManageAdminLayoutRouteImport
    }
    '/manage/_admin-layout/drafts/publish/$id': {
      id: '/manage/_admin-layout/drafts/publish/$id'
      path: '/drafts/publish/$id'
      fullPath: '/manage/drafts/publish/$id'
      preLoaderRoute: typeof ManageAdminLayoutDraftsPublishIdImport
      parentRoute: typeof ManageAdminLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface ManageAdminLayoutRouteRouteChildren {
  ManageAdminLayoutDraftsIndexRoute: typeof ManageAdminLayoutDraftsIndexRoute
  ManageAdminLayoutDraftsPublishIdRoute: typeof ManageAdminLayoutDraftsPublishIdRoute
}

const ManageAdminLayoutRouteRouteChildren: ManageAdminLayoutRouteRouteChildren =
  {
    ManageAdminLayoutDraftsIndexRoute: ManageAdminLayoutDraftsIndexRoute,
    ManageAdminLayoutDraftsPublishIdRoute:
      ManageAdminLayoutDraftsPublishIdRoute,
  }

const ManageAdminLayoutRouteRouteWithChildren =
  ManageAdminLayoutRouteRoute._addFileChildren(
    ManageAdminLayoutRouteRouteChildren,
  )

interface ManageRouteChildren {
  ManageAdminLayoutRouteRoute: typeof ManageAdminLayoutRouteRouteWithChildren
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAdminLayoutRouteRoute: ManageAdminLayoutRouteRouteWithChildren,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/manage/drafts': typeof ManageAdminLayoutDraftsIndexRoute
  '/manage/drafts/publish/$id': typeof ManageAdminLayoutDraftsPublishIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/manage/drafts': typeof ManageAdminLayoutDraftsIndexRoute
  '/manage/drafts/publish/$id': typeof ManageAdminLayoutDraftsPublishIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage/_admin-layout': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/manage/_admin-layout/drafts/': typeof ManageAdminLayoutDraftsIndexRoute
  '/manage/_admin-layout/drafts/publish/$id': typeof ManageAdminLayoutDraftsPublishIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/manage/drafts'
    | '/manage/drafts/publish/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/manage/drafts'
    | '/manage/drafts/publish/$id'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/manage/_admin-layout'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles/'
    | '/manage/_admin-layout/drafts/'
    | '/manage/_admin-layout/drafts/publish/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRoute: typeof ManageRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesSubmitRoute: typeof ArticlesSubmitRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRoute: ManageRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesSubmitRoute: ArticlesSubmitRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/manage",
        "/articles/$slug",
        "/articles/submit",
        "/articles/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/manage": {
      "filePath": "manage._admin-layout",
      "children": [
        "/manage/_admin-layout"
      ]
    },
    "/manage/_admin-layout": {
      "filePath": "manage._admin-layout/route.tsx",
      "parent": "/manage",
      "children": [
        "/manage/_admin-layout/drafts/",
        "/manage/_admin-layout/drafts/publish/$id"
      ]
    },
    "/articles/$slug": {
      "filePath": "articles/$slug.tsx"
    },
    "/articles/submit": {
      "filePath": "articles/submit.tsx"
    },
    "/articles/": {
      "filePath": "articles/index.tsx"
    },
    "/manage/_admin-layout/drafts/": {
      "filePath": "manage._admin-layout/drafts/index.tsx",
      "parent": "/manage/_admin-layout"
    },
    "/manage/_admin-layout/drafts/publish/$id": {
      "filePath": "manage._admin-layout/drafts/publish.$id.tsx",
      "parent": "/manage/_admin-layout"
    }
  }
}
ROUTE_MANIFEST_END */
