/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSubmitRouteImport } from './routes/articles/submit'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ManageAdminLayoutRouteRouteImport } from './routes/manage._admin-layout/route'
import { Route as ManageAdminLayoutPeopleRouteImport } from './routes/manage._admin-layout/people'
import { Route as ManageAdminLayoutAStatusRouteImport } from './routes/manage._admin-layout/a.$status'
import { ServerRoute as ApiUploadthingServerRouteImport } from './routes/api/uploadthing'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const ManageRouteImport = createFileRoute('/manage')()
const rootServerRouteImport = createServerRootRoute()

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSubmitRoute = ArticlesSubmitRouteImport.update({
  id: '/articles/submit',
  path: '/articles/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminLayoutRouteRoute = ManageAdminLayoutRouteRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAdminLayoutPeopleRoute = ManageAdminLayoutPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ManageAdminLayoutRouteRoute,
} as any)
const ManageAdminLayoutAStatusRoute =
  ManageAdminLayoutAStatusRouteImport.update({
    id: '/a/$status',
    path: '/a/$status',
    getParentRoute: () => ManageAdminLayoutRouteRoute,
  } as any)
const ApiUploadthingServerRoute = ApiUploadthingServerRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/manage/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/a/$status': typeof ManageAdminLayoutAStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles': typeof ArticlesIndexRoute
  '/manage/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/a/$status': typeof ManageAdminLayoutAStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage/_admin-layout': typeof ManageAdminLayoutRouteRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/submit': typeof ArticlesSubmitRoute
  '/articles/': typeof ArticlesIndexRoute
  '/manage/_admin-layout/people': typeof ManageAdminLayoutPeopleRoute
  '/manage/_admin-layout/a/$status': typeof ManageAdminLayoutAStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/manage/people'
    | '/manage/a/$status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles'
    | '/manage/people'
    | '/manage/a/$status'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/manage/_admin-layout'
    | '/articles/$slug'
    | '/articles/submit'
    | '/articles/'
    | '/manage/_admin-layout/people'
    | '/manage/_admin-layout/a/$status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRoute: typeof ManageRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesSubmitRoute: typeof ArticlesSubmitRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/uploadthing' | '/api/auth/$' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/uploadthing' | '/api/auth/$' | '/api/trpc/$'
  id: '__root__' | '/api/uploadthing' | '/api/auth/$' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUploadthingServerRoute: typeof ApiUploadthingServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/submit': {
      id: '/articles/submit'
      path: '/articles/submit'
      fullPath: '/articles/submit'
      preLoaderRoute: typeof ArticlesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/_admin-layout': {
      id: '/manage/_admin-layout'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageAdminLayoutRouteRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/_admin-layout/people': {
      id: '/manage/_admin-layout/people'
      path: '/people'
      fullPath: '/manage/people'
      preLoaderRoute: typeof ManageAdminLayoutPeopleRouteImport
      parentRoute: typeof ManageAdminLayoutRouteRoute
    }
    '/manage/_admin-layout/a/$status': {
      id: '/manage/_admin-layout/a/$status'
      path: '/a/$status'
      fullPath: '/manage/a/$status'
      preLoaderRoute: typeof ManageAdminLayoutAStatusRouteImport
      parentRoute: typeof ManageAdminLayoutRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ManageAdminLayoutRouteRouteChildren {
  ManageAdminLayoutPeopleRoute: typeof ManageAdminLayoutPeopleRoute
  ManageAdminLayoutAStatusRoute: typeof ManageAdminLayoutAStatusRoute
}

const ManageAdminLayoutRouteRouteChildren: ManageAdminLayoutRouteRouteChildren =
  {
    ManageAdminLayoutPeopleRoute: ManageAdminLayoutPeopleRoute,
    ManageAdminLayoutAStatusRoute: ManageAdminLayoutAStatusRoute,
  }

const ManageAdminLayoutRouteRouteWithChildren =
  ManageAdminLayoutRouteRoute._addFileChildren(
    ManageAdminLayoutRouteRouteChildren,
  )

interface ManageRouteChildren {
  ManageAdminLayoutRouteRoute: typeof ManageAdminLayoutRouteRouteWithChildren
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAdminLayoutRouteRoute: ManageAdminLayoutRouteRouteWithChildren,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRoute: ManageRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesSubmitRoute: ArticlesSubmitRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUploadthingServerRoute: ApiUploadthingServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
